name: 'Pack NuGet'
author: 'Jiri Polasek'
description: >-
  Determine version suffix from tag/branch and pack the project into artifacts/.
  
inputs:
  projectPath:
    description: "Path to the project file (e.g. src/ProjectName.csproj)"
    required: true
  version:
    description: "Version"
    required: true
  workspace:
    description: "github.workspace (path to repo root)"
    required: true
  configuration:
    description: "Build configuration (e.g. Release, Debug)"
    default: "Release"

runs:
  using: "composite"
  steps:
    - name: Pack
      shell: pwsh
      run: |
        $actionDir = "${{ github.action_path }}"
        & "$actionDir/pack.ps1" `
          -ProjectPath     '${{ inputs.projectPath }}' `
          -Version         '${{ inputs.version }}' `
          -Workspace       '${{ inputs.workspace }}' `
          -Configuration   '${{ inputs.configuration }}'