name: 'Get Version'
author: 'Jiri Polasek'
description: >-
    'Determines semantic version based on Git tags and branch context'

inputs:
  github-event-name:
    description: 'GitHub event name (defaults to GITHUB_EVENT_NAME environment variable)'
    required: false
    default: ''
  github-ref:
    description: 'GitHub reference (defaults to GITHUB_REF environment variable)'
    required: false
    default: ''
  version-override:
    description: 'Manual version input for workflow_dispatch events'
    required: false
    default: ''

outputs:
  version:
    description: 'The calculated semantic version'
    value: ${{ steps.get-version.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Get Version
      id: get-version
      shell: pwsh
      run: |
        $scriptPath = Join-Path $env:GITHUB_ACTION_PATH "Get-Version.ps1"
        $version = & $scriptPath `
            -GitHubEventName "${{ inputs.github-event-name }}" `
            -GitHubRef "${{ inputs.github-ref }}" `
            -InputsVersion "${{ inputs.version-override }}"
        
        "Version: $version" >> $env:GITHUB_STEP_SUMMARY
        Write-Host "Version (YML): $version"
        "version=$version" | Out-File -Append -FilePath $env:GITHUB_OUTPUT

branding:
  icon: 'tag'
  color: 'blue'